apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackabolobend
spec:
  selector:
      matchLabels:
        app: hackabolobend
  replicas: 4
  template:
      metadata:
        labels:
            app: hackabolobend
      spec:
        containers:
        - name: hackabolobend
          image: hackaboloacr.azurecr.io/wapol-infosec/hackabolo:{{LATEST_BUILD}}
          imagePullPolicy: Always
          env:
          - name: CONNECTION_STRING
            value: 'mongodb://hackabolomongodb.default.svc.cluster.local/admin'
          - name: TEST_CONNECTION_STRING
            value: 'mongodb://hackabolomongodb.default.svc.cluster.local/admin'
          - name: HTTP_PORT
            value: '8081'
          - name: OAUTH_CLIENT_ID
            value: 'VbDysyoGDPqUw6bNbJofPMHaa6fgBnfX'
          - name: OAUTH_CLIENT_SECRET
            value: 'cdbb2f2a4d1ba9cc249d5309ea399fe79a259512680fe32e307e42945451497a'
          - name: PASSWORD_LENGTH
            value: '10'
          - name: SALT
            value: 'UsethissalttomakepasswordsmoresecurebecauseusersarelazY'
          - name: TOKEN_USER_EXPIRY
            value: '1200'
          - name: ROOTPW
            value: 'devSECarch'
          ports:
          - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: hackabolobend
spec:
  type: LoadBalancer
  ports:
  - port: 8081
  selector:
    app: hackabolobend


